// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.15.7
// source: mdm.proto

package mdm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_mdm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_mdm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{1}
}

func (x *EmptyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalResponse) Reset() {
	*x = TotalResponse{}
	mi := &file_mdm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalResponse) ProtoMessage() {}

func (x *TotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalResponse.ProtoReflect.Descriptor instead.
func (*TotalResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{2}
}

func (x *TotalResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MdmBrandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       int64                  `protobuf:"varint,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`      // 主键
	BrandName     string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"` //品牌简称
	BrandLogo     string                 `protobuf:"bytes,3,opt,name=brand_logo,json=brandLogo,proto3" json:"brand_logo,omitempty"`
	BrandTitle    string                 `protobuf:"bytes,4,opt,name=brand_title,json=brandTitle,proto3" json:"brand_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdmBrandInfo) Reset() {
	*x = MdmBrandInfo{}
	mi := &file_mdm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdmBrandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdmBrandInfo) ProtoMessage() {}

func (x *MdmBrandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdmBrandInfo.ProtoReflect.Descriptor instead.
func (*MdmBrandInfo) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{3}
}

func (x *MdmBrandInfo) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *MdmBrandInfo) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *MdmBrandInfo) GetBrandLogo() string {
	if x != nil {
		return x.BrandLogo
	}
	return ""
}

func (x *MdmBrandInfo) GetBrandTitle() string {
	if x != nil {
		return x.BrandTitle
	}
	return ""
}

// *****************品牌列表请求返回******************
type MdmBrandListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	BrandId       []int64                `protobuf:"varint,4,rep,packed,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdmBrandListRequest) Reset() {
	*x = MdmBrandListRequest{}
	mi := &file_mdm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdmBrandListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdmBrandListRequest) ProtoMessage() {}

func (x *MdmBrandListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdmBrandListRequest.ProtoReflect.Descriptor instead.
func (*MdmBrandListRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{4}
}

func (x *MdmBrandListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MdmBrandListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *MdmBrandListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *MdmBrandListRequest) GetBrandId() []int64 {
	if x != nil {
		return x.BrandId
	}
	return nil
}

type MdmBrandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MdmBrandInfo        `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdmBrandListResponse) Reset() {
	*x = MdmBrandListResponse{}
	mi := &file_mdm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdmBrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdmBrandListResponse) ProtoMessage() {}

func (x *MdmBrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdmBrandListResponse.ProtoReflect.Descriptor instead.
func (*MdmBrandListResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{5}
}

func (x *MdmBrandListResponse) GetList() []*MdmBrandInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// *****************品牌信息请求返回******************
type MdmBrandInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       int64                  `protobuf:"varint,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`      // 主键
	BrandName     string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"` //品牌代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdmBrandInfoRequest) Reset() {
	*x = MdmBrandInfoRequest{}
	mi := &file_mdm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdmBrandInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdmBrandInfoRequest) ProtoMessage() {}

func (x *MdmBrandInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdmBrandInfoRequest.ProtoReflect.Descriptor instead.
func (*MdmBrandInfoRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{6}
}

func (x *MdmBrandInfoRequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *MdmBrandInfoRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

var File_mdm_proto protoreflect.FileDescriptor

const file_mdm_proto_rawDesc = "" +
	"\n" +
	"\tmdm.proto\x12\x03mdm\"\x0e\n" +
	"\fEmptyRequest\"5\n" +
	"\rEmptyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"%\n" +
	"\rTotalResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"\x88\x01\n" +
	"\fMdmBrandInfo\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12\x1d\n" +
	"\n" +
	"brand_logo\x18\x03 \x01(\tR\tbrandLogo\x12\x1f\n" +
	"\vbrand_title\x18\x04 \x01(\tR\n" +
	"brandTitle\"z\n" +
	"\x13MdmBrandListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\aorderBy\x18\x03 \x01(\tR\aorderBy\x12\x19\n" +
	"\bbrand_id\x18\x04 \x03(\x03R\abrandId\"=\n" +
	"\x14MdmBrandListResponse\x12%\n" +
	"\x04list\x18\x04 \x03(\v2\x11.mdm.MdmBrandInfoR\x04list\"O\n" +
	"\x13MdmBrandInfoRequest\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName2\xc4\x02\n" +
	"\x0fMdmBrandService\x12=\n" +
	"\rMdmBrandCount\x12\x18.mdm.MdmBrandListRequest\x1a\x12.mdm.TotalResponse\x12C\n" +
	"\fMdmBrandList\x12\x18.mdm.MdmBrandListRequest\x1a\x19.mdm.MdmBrandListResponse\x12>\n" +
	"\x0fMdmBrandDetails\x12\x18.mdm.MdmBrandInfoRequest\x1a\x11.mdm.MdmBrandInfo\x124\n" +
	"\vMdmBrandAdd\x12\x11.mdm.MdmBrandInfo\x1a\x12.mdm.EmptyResponse\x127\n" +
	"\x0eMdmBrandUpdate\x12\x11.mdm.MdmBrandInfo\x1a\x12.mdm.EmptyResponseB\aZ\x05./mdmb\x06proto3"

var (
	file_mdm_proto_rawDescOnce sync.Once
	file_mdm_proto_rawDescData []byte
)

func file_mdm_proto_rawDescGZIP() []byte {
	file_mdm_proto_rawDescOnce.Do(func() {
		file_mdm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mdm_proto_rawDesc), len(file_mdm_proto_rawDesc)))
	})
	return file_mdm_proto_rawDescData
}

var file_mdm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mdm_proto_goTypes = []any{
	(*EmptyRequest)(nil),         // 0: mdm.EmptyRequest
	(*EmptyResponse)(nil),        // 1: mdm.EmptyResponse
	(*TotalResponse)(nil),        // 2: mdm.TotalResponse
	(*MdmBrandInfo)(nil),         // 3: mdm.MdmBrandInfo
	(*MdmBrandListRequest)(nil),  // 4: mdm.MdmBrandListRequest
	(*MdmBrandListResponse)(nil), // 5: mdm.MdmBrandListResponse
	(*MdmBrandInfoRequest)(nil),  // 6: mdm.MdmBrandInfoRequest
}
var file_mdm_proto_depIdxs = []int32{
	3, // 0: mdm.MdmBrandListResponse.list:type_name -> mdm.MdmBrandInfo
	4, // 1: mdm.MdmBrandService.MdmBrandCount:input_type -> mdm.MdmBrandListRequest
	4, // 2: mdm.MdmBrandService.MdmBrandList:input_type -> mdm.MdmBrandListRequest
	6, // 3: mdm.MdmBrandService.MdmBrandDetails:input_type -> mdm.MdmBrandInfoRequest
	3, // 4: mdm.MdmBrandService.MdmBrandAdd:input_type -> mdm.MdmBrandInfo
	3, // 5: mdm.MdmBrandService.MdmBrandUpdate:input_type -> mdm.MdmBrandInfo
	2, // 6: mdm.MdmBrandService.MdmBrandCount:output_type -> mdm.TotalResponse
	5, // 7: mdm.MdmBrandService.MdmBrandList:output_type -> mdm.MdmBrandListResponse
	3, // 8: mdm.MdmBrandService.MdmBrandDetails:output_type -> mdm.MdmBrandInfo
	1, // 9: mdm.MdmBrandService.MdmBrandAdd:output_type -> mdm.EmptyResponse
	1, // 10: mdm.MdmBrandService.MdmBrandUpdate:output_type -> mdm.EmptyResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mdm_proto_init() }
func file_mdm_proto_init() {
	if File_mdm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mdm_proto_rawDesc), len(file_mdm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mdm_proto_goTypes,
		DependencyIndexes: file_mdm_proto_depIdxs,
		MessageInfos:      file_mdm_proto_msgTypes,
	}.Build()
	File_mdm_proto = out.File
	file_mdm_proto_goTypes = nil
	file_mdm_proto_depIdxs = nil
}
