// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.7
// source: mdm.proto

package mdm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MdmBrandService_MdmBrandCount_FullMethodName   = "/mdm.MdmBrandService/MdmBrandCount"
	MdmBrandService_MdmBrandList_FullMethodName    = "/mdm.MdmBrandService/MdmBrandList"
	MdmBrandService_MdmBrandDetails_FullMethodName = "/mdm.MdmBrandService/MdmBrandDetails"
	MdmBrandService_MdmBrandAdd_FullMethodName     = "/mdm.MdmBrandService/MdmBrandAdd"
	MdmBrandService_MdmBrandUpdate_FullMethodName  = "/mdm.MdmBrandService/MdmBrandUpdate"
)

// MdmBrandServiceClient is the client API for MdmBrandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 品牌服务接口
type MdmBrandServiceClient interface {
	// 品牌数量
	MdmBrandCount(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*TotalResponse, error)
	// 品牌列表
	MdmBrandList(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*MdmBrandListResponse, error)
	// 品牌信息
	MdmBrandDetails(ctx context.Context, in *MdmBrandInfoRequest, opts ...grpc.CallOption) (*MdmBrandInfo, error)
	// 品牌增加
	MdmBrandAdd(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error)
	// 品牌修改
	MdmBrandUpdate(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type mdmBrandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMdmBrandServiceClient(cc grpc.ClientConnInterface) MdmBrandServiceClient {
	return &mdmBrandServiceClient{cc}
}

func (c *mdmBrandServiceClient) MdmBrandCount(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*TotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalResponse)
	err := c.cc.Invoke(ctx, MdmBrandService_MdmBrandCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmBrandServiceClient) MdmBrandList(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*MdmBrandListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MdmBrandListResponse)
	err := c.cc.Invoke(ctx, MdmBrandService_MdmBrandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmBrandServiceClient) MdmBrandDetails(ctx context.Context, in *MdmBrandInfoRequest, opts ...grpc.CallOption) (*MdmBrandInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MdmBrandInfo)
	err := c.cc.Invoke(ctx, MdmBrandService_MdmBrandDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmBrandServiceClient) MdmBrandAdd(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, MdmBrandService_MdmBrandAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmBrandServiceClient) MdmBrandUpdate(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, MdmBrandService_MdmBrandUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdmBrandServiceServer is the server API for MdmBrandService service.
// All implementations must embed UnimplementedMdmBrandServiceServer
// for forward compatibility.
//
// 品牌服务接口
type MdmBrandServiceServer interface {
	// 品牌数量
	MdmBrandCount(context.Context, *MdmBrandListRequest) (*TotalResponse, error)
	// 品牌列表
	MdmBrandList(context.Context, *MdmBrandListRequest) (*MdmBrandListResponse, error)
	// 品牌信息
	MdmBrandDetails(context.Context, *MdmBrandInfoRequest) (*MdmBrandInfo, error)
	// 品牌增加
	MdmBrandAdd(context.Context, *MdmBrandInfo) (*EmptyResponse, error)
	// 品牌修改
	MdmBrandUpdate(context.Context, *MdmBrandInfo) (*EmptyResponse, error)
	mustEmbedUnimplementedMdmBrandServiceServer()
}

// UnimplementedMdmBrandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMdmBrandServiceServer struct{}

func (UnimplementedMdmBrandServiceServer) MdmBrandCount(context.Context, *MdmBrandListRequest) (*TotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdmBrandCount not implemented")
}
func (UnimplementedMdmBrandServiceServer) MdmBrandList(context.Context, *MdmBrandListRequest) (*MdmBrandListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdmBrandList not implemented")
}
func (UnimplementedMdmBrandServiceServer) MdmBrandDetails(context.Context, *MdmBrandInfoRequest) (*MdmBrandInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdmBrandDetails not implemented")
}
func (UnimplementedMdmBrandServiceServer) MdmBrandAdd(context.Context, *MdmBrandInfo) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdmBrandAdd not implemented")
}
func (UnimplementedMdmBrandServiceServer) MdmBrandUpdate(context.Context, *MdmBrandInfo) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MdmBrandUpdate not implemented")
}
func (UnimplementedMdmBrandServiceServer) mustEmbedUnimplementedMdmBrandServiceServer() {}
func (UnimplementedMdmBrandServiceServer) testEmbeddedByValue()                         {}

// UnsafeMdmBrandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdmBrandServiceServer will
// result in compilation errors.
type UnsafeMdmBrandServiceServer interface {
	mustEmbedUnimplementedMdmBrandServiceServer()
}

func RegisterMdmBrandServiceServer(s grpc.ServiceRegistrar, srv MdmBrandServiceServer) {
	// If the following call pancis, it indicates UnimplementedMdmBrandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MdmBrandService_ServiceDesc, srv)
}

func _MdmBrandService_MdmBrandCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdmBrandListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmBrandServiceServer).MdmBrandCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmBrandService_MdmBrandCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmBrandServiceServer).MdmBrandCount(ctx, req.(*MdmBrandListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmBrandService_MdmBrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdmBrandListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmBrandServiceServer).MdmBrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmBrandService_MdmBrandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmBrandServiceServer).MdmBrandList(ctx, req.(*MdmBrandListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmBrandService_MdmBrandDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdmBrandInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmBrandServiceServer).MdmBrandDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmBrandService_MdmBrandDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmBrandServiceServer).MdmBrandDetails(ctx, req.(*MdmBrandInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmBrandService_MdmBrandAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdmBrandInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmBrandServiceServer).MdmBrandAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmBrandService_MdmBrandAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmBrandServiceServer).MdmBrandAdd(ctx, req.(*MdmBrandInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmBrandService_MdmBrandUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MdmBrandInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmBrandServiceServer).MdmBrandUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmBrandService_MdmBrandUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmBrandServiceServer).MdmBrandUpdate(ctx, req.(*MdmBrandInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// MdmBrandService_ServiceDesc is the grpc.ServiceDesc for MdmBrandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdmBrandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdm.MdmBrandService",
	HandlerType: (*MdmBrandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MdmBrandCount",
			Handler:    _MdmBrandService_MdmBrandCount_Handler,
		},
		{
			MethodName: "MdmBrandList",
			Handler:    _MdmBrandService_MdmBrandList_Handler,
		},
		{
			MethodName: "MdmBrandDetails",
			Handler:    _MdmBrandService_MdmBrandDetails_Handler,
		},
		{
			MethodName: "MdmBrandAdd",
			Handler:    _MdmBrandService_MdmBrandAdd_Handler,
		},
		{
			MethodName: "MdmBrandUpdate",
			Handler:    _MdmBrandService_MdmBrandUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdm.proto",
}
