// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"his/mdm/model/brands/ent/mdmbrands"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 基础物料品牌222
type MdmBrands struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 品牌名称
	BrandName string `json:"brand_name,omitempty"`
	// 品牌logo222
	BrandLogo string `json:"brand_logo,omitempty"`
	// 品牌标题
	BrandTitle   string `json:"brand_title,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MdmBrands) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mdmbrands.FieldID:
			values[i] = new(sql.NullInt64)
		case mdmbrands.FieldBrandName, mdmbrands.FieldBrandLogo, mdmbrands.FieldBrandTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MdmBrands fields.
func (_m *MdmBrands) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mdmbrands.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mdmbrands.FieldBrandName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand_name", values[i])
			} else if value.Valid {
				_m.BrandName = value.String
			}
		case mdmbrands.FieldBrandLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand_logo", values[i])
			} else if value.Valid {
				_m.BrandLogo = value.String
			}
		case mdmbrands.FieldBrandTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand_title", values[i])
			} else if value.Valid {
				_m.BrandTitle = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MdmBrands.
// This includes values selected through modifiers, order, etc.
func (_m *MdmBrands) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MdmBrands.
// Note that you need to call MdmBrands.Unwrap() before calling this method if this MdmBrands
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MdmBrands) Update() *MdmBrandsUpdateOne {
	return NewMdmBrandsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MdmBrands entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MdmBrands) Unwrap() *MdmBrands {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MdmBrands is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MdmBrands) String() string {
	var builder strings.Builder
	builder.WriteString("MdmBrands(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("brand_name=")
	builder.WriteString(_m.BrandName)
	builder.WriteString(", ")
	builder.WriteString("brand_logo=")
	builder.WriteString(_m.BrandLogo)
	builder.WriteString(", ")
	builder.WriteString("brand_title=")
	builder.WriteString(_m.BrandTitle)
	builder.WriteByte(')')
	return builder.String()
}

// MdmBrandsSlice is a parsable slice of MdmBrands.
type MdmBrandsSlice []*MdmBrands
