// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"his/mdm/model/brands/ent/mdmbrands"
	"his/mdm/model/brands/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MdmBrandsUpdate is the builder for updating MdmBrands entities.
type MdmBrandsUpdate struct {
	config
	hooks    []Hook
	mutation *MdmBrandsMutation
}

// Where appends a list predicates to the MdmBrandsUpdate builder.
func (_u *MdmBrandsUpdate) Where(ps ...predicate.MdmBrands) *MdmBrandsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBrandName sets the "brand_name" field.
func (_u *MdmBrandsUpdate) SetBrandName(v string) *MdmBrandsUpdate {
	_u.mutation.SetBrandName(v)
	return _u
}

// SetNillableBrandName sets the "brand_name" field if the given value is not nil.
func (_u *MdmBrandsUpdate) SetNillableBrandName(v *string) *MdmBrandsUpdate {
	if v != nil {
		_u.SetBrandName(*v)
	}
	return _u
}

// SetBrandLogo sets the "brand_logo" field.
func (_u *MdmBrandsUpdate) SetBrandLogo(v string) *MdmBrandsUpdate {
	_u.mutation.SetBrandLogo(v)
	return _u
}

// SetNillableBrandLogo sets the "brand_logo" field if the given value is not nil.
func (_u *MdmBrandsUpdate) SetNillableBrandLogo(v *string) *MdmBrandsUpdate {
	if v != nil {
		_u.SetBrandLogo(*v)
	}
	return _u
}

// SetBrandTitle sets the "brand_title" field.
func (_u *MdmBrandsUpdate) SetBrandTitle(v string) *MdmBrandsUpdate {
	_u.mutation.SetBrandTitle(v)
	return _u
}

// SetNillableBrandTitle sets the "brand_title" field if the given value is not nil.
func (_u *MdmBrandsUpdate) SetNillableBrandTitle(v *string) *MdmBrandsUpdate {
	if v != nil {
		_u.SetBrandTitle(*v)
	}
	return _u
}

// Mutation returns the MdmBrandsMutation object of the builder.
func (_u *MdmBrandsUpdate) Mutation() *MdmBrandsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MdmBrandsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MdmBrandsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MdmBrandsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MdmBrandsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MdmBrandsUpdate) check() error {
	if v, ok := _u.mutation.BrandName(); ok {
		if err := mdmbrands.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandLogo(); ok {
		if err := mdmbrands.BrandLogoValidator(v); err != nil {
			return &ValidationError{Name: "brand_logo", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_logo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandTitle(); ok {
		if err := mdmbrands.BrandTitleValidator(v); err != nil {
			return &ValidationError{Name: "brand_title", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_title": %w`, err)}
		}
	}
	return nil
}

func (_u *MdmBrandsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mdmbrands.Table, mdmbrands.Columns, sqlgraph.NewFieldSpec(mdmbrands.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrandName(); ok {
		_spec.SetField(mdmbrands.FieldBrandName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandLogo(); ok {
		_spec.SetField(mdmbrands.FieldBrandLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandTitle(); ok {
		_spec.SetField(mdmbrands.FieldBrandTitle, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mdmbrands.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MdmBrandsUpdateOne is the builder for updating a single MdmBrands entity.
type MdmBrandsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MdmBrandsMutation
}

// SetBrandName sets the "brand_name" field.
func (_u *MdmBrandsUpdateOne) SetBrandName(v string) *MdmBrandsUpdateOne {
	_u.mutation.SetBrandName(v)
	return _u
}

// SetNillableBrandName sets the "brand_name" field if the given value is not nil.
func (_u *MdmBrandsUpdateOne) SetNillableBrandName(v *string) *MdmBrandsUpdateOne {
	if v != nil {
		_u.SetBrandName(*v)
	}
	return _u
}

// SetBrandLogo sets the "brand_logo" field.
func (_u *MdmBrandsUpdateOne) SetBrandLogo(v string) *MdmBrandsUpdateOne {
	_u.mutation.SetBrandLogo(v)
	return _u
}

// SetNillableBrandLogo sets the "brand_logo" field if the given value is not nil.
func (_u *MdmBrandsUpdateOne) SetNillableBrandLogo(v *string) *MdmBrandsUpdateOne {
	if v != nil {
		_u.SetBrandLogo(*v)
	}
	return _u
}

// SetBrandTitle sets the "brand_title" field.
func (_u *MdmBrandsUpdateOne) SetBrandTitle(v string) *MdmBrandsUpdateOne {
	_u.mutation.SetBrandTitle(v)
	return _u
}

// SetNillableBrandTitle sets the "brand_title" field if the given value is not nil.
func (_u *MdmBrandsUpdateOne) SetNillableBrandTitle(v *string) *MdmBrandsUpdateOne {
	if v != nil {
		_u.SetBrandTitle(*v)
	}
	return _u
}

// Mutation returns the MdmBrandsMutation object of the builder.
func (_u *MdmBrandsUpdateOne) Mutation() *MdmBrandsMutation {
	return _u.mutation
}

// Where appends a list predicates to the MdmBrandsUpdate builder.
func (_u *MdmBrandsUpdateOne) Where(ps ...predicate.MdmBrands) *MdmBrandsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MdmBrandsUpdateOne) Select(field string, fields ...string) *MdmBrandsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MdmBrands entity.
func (_u *MdmBrandsUpdateOne) Save(ctx context.Context) (*MdmBrands, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MdmBrandsUpdateOne) SaveX(ctx context.Context) *MdmBrands {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MdmBrandsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MdmBrandsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MdmBrandsUpdateOne) check() error {
	if v, ok := _u.mutation.BrandName(); ok {
		if err := mdmbrands.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandLogo(); ok {
		if err := mdmbrands.BrandLogoValidator(v); err != nil {
			return &ValidationError{Name: "brand_logo", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_logo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BrandTitle(); ok {
		if err := mdmbrands.BrandTitleValidator(v); err != nil {
			return &ValidationError{Name: "brand_title", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_title": %w`, err)}
		}
	}
	return nil
}

func (_u *MdmBrandsUpdateOne) sqlSave(ctx context.Context) (_node *MdmBrands, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mdmbrands.Table, mdmbrands.Columns, sqlgraph.NewFieldSpec(mdmbrands.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MdmBrands.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mdmbrands.FieldID)
		for _, f := range fields {
			if !mdmbrands.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mdmbrands.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrandName(); ok {
		_spec.SetField(mdmbrands.FieldBrandName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandLogo(); ok {
		_spec.SetField(mdmbrands.FieldBrandLogo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrandTitle(); ok {
		_spec.SetField(mdmbrands.FieldBrandTitle, field.TypeString, value)
	}
	_node = &MdmBrands{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mdmbrands.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
