// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"his/mdm/model/brands/ent/mdmbrands"
	"his/mdm/model/brands/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MdmBrandsDelete is the builder for deleting a MdmBrands entity.
type MdmBrandsDelete struct {
	config
	hooks    []Hook
	mutation *MdmBrandsMutation
}

// Where appends a list predicates to the MdmBrandsDelete builder.
func (_d *MdmBrandsDelete) Where(ps ...predicate.MdmBrands) *MdmBrandsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MdmBrandsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MdmBrandsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MdmBrandsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mdmbrands.Table, sqlgraph.NewFieldSpec(mdmbrands.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MdmBrandsDeleteOne is the builder for deleting a single MdmBrands entity.
type MdmBrandsDeleteOne struct {
	_d *MdmBrandsDelete
}

// Where appends a list predicates to the MdmBrandsDelete builder.
func (_d *MdmBrandsDeleteOne) Where(ps ...predicate.MdmBrands) *MdmBrandsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MdmBrandsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mdmbrands.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MdmBrandsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
