// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"his/mdm/model/brands/ent/mdmbrands"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MdmBrandsCreate is the builder for creating a MdmBrands entity.
type MdmBrandsCreate struct {
	config
	mutation *MdmBrandsMutation
	hooks    []Hook
}

// SetBrandName sets the "brand_name" field.
func (_c *MdmBrandsCreate) SetBrandName(v string) *MdmBrandsCreate {
	_c.mutation.SetBrandName(v)
	return _c
}

// SetBrandLogo sets the "brand_logo" field.
func (_c *MdmBrandsCreate) SetBrandLogo(v string) *MdmBrandsCreate {
	_c.mutation.SetBrandLogo(v)
	return _c
}

// SetNillableBrandLogo sets the "brand_logo" field if the given value is not nil.
func (_c *MdmBrandsCreate) SetNillableBrandLogo(v *string) *MdmBrandsCreate {
	if v != nil {
		_c.SetBrandLogo(*v)
	}
	return _c
}

// SetBrandTitle sets the "brand_title" field.
func (_c *MdmBrandsCreate) SetBrandTitle(v string) *MdmBrandsCreate {
	_c.mutation.SetBrandTitle(v)
	return _c
}

// SetNillableBrandTitle sets the "brand_title" field if the given value is not nil.
func (_c *MdmBrandsCreate) SetNillableBrandTitle(v *string) *MdmBrandsCreate {
	if v != nil {
		_c.SetBrandTitle(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MdmBrandsCreate) SetID(v int) *MdmBrandsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MdmBrandsMutation object of the builder.
func (_c *MdmBrandsCreate) Mutation() *MdmBrandsMutation {
	return _c.mutation
}

// Save creates the MdmBrands in the database.
func (_c *MdmBrandsCreate) Save(ctx context.Context) (*MdmBrands, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MdmBrandsCreate) SaveX(ctx context.Context) *MdmBrands {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MdmBrandsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MdmBrandsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MdmBrandsCreate) defaults() {
	if _, ok := _c.mutation.BrandLogo(); !ok {
		v := mdmbrands.DefaultBrandLogo
		_c.mutation.SetBrandLogo(v)
	}
	if _, ok := _c.mutation.BrandTitle(); !ok {
		v := mdmbrands.DefaultBrandTitle
		_c.mutation.SetBrandTitle(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MdmBrandsCreate) check() error {
	if _, ok := _c.mutation.BrandName(); !ok {
		return &ValidationError{Name: "brand_name", err: errors.New(`ent: missing required field "MdmBrands.brand_name"`)}
	}
	if v, ok := _c.mutation.BrandName(); ok {
		if err := mdmbrands.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BrandLogo(); !ok {
		return &ValidationError{Name: "brand_logo", err: errors.New(`ent: missing required field "MdmBrands.brand_logo"`)}
	}
	if v, ok := _c.mutation.BrandLogo(); ok {
		if err := mdmbrands.BrandLogoValidator(v); err != nil {
			return &ValidationError{Name: "brand_logo", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_logo": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BrandTitle(); !ok {
		return &ValidationError{Name: "brand_title", err: errors.New(`ent: missing required field "MdmBrands.brand_title"`)}
	}
	if v, ok := _c.mutation.BrandTitle(); ok {
		if err := mdmbrands.BrandTitleValidator(v); err != nil {
			return &ValidationError{Name: "brand_title", err: fmt.Errorf(`ent: validator failed for field "MdmBrands.brand_title": %w`, err)}
		}
	}
	return nil
}

func (_c *MdmBrandsCreate) sqlSave(ctx context.Context) (*MdmBrands, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MdmBrandsCreate) createSpec() (*MdmBrands, *sqlgraph.CreateSpec) {
	var (
		_node = &MdmBrands{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mdmbrands.Table, sqlgraph.NewFieldSpec(mdmbrands.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.BrandName(); ok {
		_spec.SetField(mdmbrands.FieldBrandName, field.TypeString, value)
		_node.BrandName = value
	}
	if value, ok := _c.mutation.BrandLogo(); ok {
		_spec.SetField(mdmbrands.FieldBrandLogo, field.TypeString, value)
		_node.BrandLogo = value
	}
	if value, ok := _c.mutation.BrandTitle(); ok {
		_spec.SetField(mdmbrands.FieldBrandTitle, field.TypeString, value)
		_node.BrandTitle = value
	}
	return _node, _spec
}

// MdmBrandsCreateBulk is the builder for creating many MdmBrands entities in bulk.
type MdmBrandsCreateBulk struct {
	config
	err      error
	builders []*MdmBrandsCreate
}

// Save creates the MdmBrands entities in the database.
func (_c *MdmBrandsCreateBulk) Save(ctx context.Context) ([]*MdmBrands, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MdmBrands, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MdmBrandsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MdmBrandsCreateBulk) SaveX(ctx context.Context) []*MdmBrands {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MdmBrandsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MdmBrandsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
