// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"his/mdm/model/brands/ent/mdmbrands"
	"his/mdm/model/brands/ent/predicate"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMdmBrands = "MdmBrands"
)

// MdmBrandsMutation represents an operation that mutates the MdmBrands nodes in the graph.
type MdmBrandsMutation struct {
	config
	op            Op
	typ           string
	id            *int
	brand_name    *string
	brand_logo    *string
	brand_title   *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MdmBrands, error)
	predicates    []predicate.MdmBrands
}

var _ ent.Mutation = (*MdmBrandsMutation)(nil)

// mdmbrandsOption allows management of the mutation configuration using functional options.
type mdmbrandsOption func(*MdmBrandsMutation)

// newMdmBrandsMutation creates new mutation for the MdmBrands entity.
func newMdmBrandsMutation(c config, op Op, opts ...mdmbrandsOption) *MdmBrandsMutation {
	m := &MdmBrandsMutation{
		config:        c,
		op:            op,
		typ:           TypeMdmBrands,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMdmBrandsID sets the ID field of the mutation.
func withMdmBrandsID(id int) mdmbrandsOption {
	return func(m *MdmBrandsMutation) {
		var (
			err   error
			once  sync.Once
			value *MdmBrands
		)
		m.oldValue = func(ctx context.Context) (*MdmBrands, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MdmBrands.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMdmBrands sets the old MdmBrands of the mutation.
func withMdmBrands(node *MdmBrands) mdmbrandsOption {
	return func(m *MdmBrandsMutation) {
		m.oldValue = func(context.Context) (*MdmBrands, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MdmBrandsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MdmBrandsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of MdmBrands entities.
func (m *MdmBrandsMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MdmBrandsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MdmBrandsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MdmBrands.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBrandName sets the "brand_name" field.
func (m *MdmBrandsMutation) SetBrandName(s string) {
	m.brand_name = &s
}

// BrandName returns the value of the "brand_name" field in the mutation.
func (m *MdmBrandsMutation) BrandName() (r string, exists bool) {
	v := m.brand_name
	if v == nil {
		return
	}
	return *v, true
}

// OldBrandName returns the old "brand_name" field's value of the MdmBrands entity.
// If the MdmBrands object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MdmBrandsMutation) OldBrandName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrandName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrandName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrandName: %w", err)
	}
	return oldValue.BrandName, nil
}

// ResetBrandName resets all changes to the "brand_name" field.
func (m *MdmBrandsMutation) ResetBrandName() {
	m.brand_name = nil
}

// SetBrandLogo sets the "brand_logo" field.
func (m *MdmBrandsMutation) SetBrandLogo(s string) {
	m.brand_logo = &s
}

// BrandLogo returns the value of the "brand_logo" field in the mutation.
func (m *MdmBrandsMutation) BrandLogo() (r string, exists bool) {
	v := m.brand_logo
	if v == nil {
		return
	}
	return *v, true
}

// OldBrandLogo returns the old "brand_logo" field's value of the MdmBrands entity.
// If the MdmBrands object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MdmBrandsMutation) OldBrandLogo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrandLogo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrandLogo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrandLogo: %w", err)
	}
	return oldValue.BrandLogo, nil
}

// ResetBrandLogo resets all changes to the "brand_logo" field.
func (m *MdmBrandsMutation) ResetBrandLogo() {
	m.brand_logo = nil
}

// SetBrandTitle sets the "brand_title" field.
func (m *MdmBrandsMutation) SetBrandTitle(s string) {
	m.brand_title = &s
}

// BrandTitle returns the value of the "brand_title" field in the mutation.
func (m *MdmBrandsMutation) BrandTitle() (r string, exists bool) {
	v := m.brand_title
	if v == nil {
		return
	}
	return *v, true
}

// OldBrandTitle returns the old "brand_title" field's value of the MdmBrands entity.
// If the MdmBrands object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MdmBrandsMutation) OldBrandTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrandTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrandTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrandTitle: %w", err)
	}
	return oldValue.BrandTitle, nil
}

// ResetBrandTitle resets all changes to the "brand_title" field.
func (m *MdmBrandsMutation) ResetBrandTitle() {
	m.brand_title = nil
}

// Where appends a list predicates to the MdmBrandsMutation builder.
func (m *MdmBrandsMutation) Where(ps ...predicate.MdmBrands) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MdmBrandsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MdmBrandsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MdmBrands, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MdmBrandsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MdmBrandsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MdmBrands).
func (m *MdmBrandsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MdmBrandsMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.brand_name != nil {
		fields = append(fields, mdmbrands.FieldBrandName)
	}
	if m.brand_logo != nil {
		fields = append(fields, mdmbrands.FieldBrandLogo)
	}
	if m.brand_title != nil {
		fields = append(fields, mdmbrands.FieldBrandTitle)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MdmBrandsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mdmbrands.FieldBrandName:
		return m.BrandName()
	case mdmbrands.FieldBrandLogo:
		return m.BrandLogo()
	case mdmbrands.FieldBrandTitle:
		return m.BrandTitle()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MdmBrandsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mdmbrands.FieldBrandName:
		return m.OldBrandName(ctx)
	case mdmbrands.FieldBrandLogo:
		return m.OldBrandLogo(ctx)
	case mdmbrands.FieldBrandTitle:
		return m.OldBrandTitle(ctx)
	}
	return nil, fmt.Errorf("unknown MdmBrands field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MdmBrandsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mdmbrands.FieldBrandName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrandName(v)
		return nil
	case mdmbrands.FieldBrandLogo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrandLogo(v)
		return nil
	case mdmbrands.FieldBrandTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrandTitle(v)
		return nil
	}
	return fmt.Errorf("unknown MdmBrands field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MdmBrandsMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MdmBrandsMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MdmBrandsMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown MdmBrands numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MdmBrandsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MdmBrandsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MdmBrandsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown MdmBrands nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MdmBrandsMutation) ResetField(name string) error {
	switch name {
	case mdmbrands.FieldBrandName:
		m.ResetBrandName()
		return nil
	case mdmbrands.FieldBrandLogo:
		m.ResetBrandLogo()
		return nil
	case mdmbrands.FieldBrandTitle:
		m.ResetBrandTitle()
		return nil
	}
	return fmt.Errorf("unknown MdmBrands field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MdmBrandsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MdmBrandsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MdmBrandsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MdmBrandsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MdmBrandsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MdmBrandsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MdmBrandsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MdmBrands unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MdmBrandsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MdmBrands edge %s", name)
}
