// Code generated by ent, DO NOT EDIT.

package ent

import (
	"his/mdm/model/brands/ent/mdmbrands"
	"his/mdm/model/brands/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mdmbrandsFields := schema.MdmBrands{}.Fields()
	_ = mdmbrandsFields
	// mdmbrandsDescBrandName is the schema descriptor for brand_name field.
	mdmbrandsDescBrandName := mdmbrandsFields[1].Descriptor()
	// mdmbrands.BrandNameValidator is a validator for the "brand_name" field. It is called by the builders before save.
	mdmbrands.BrandNameValidator = func() func(string) error {
		validators := mdmbrandsDescBrandName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(brand_name string) error {
			for _, fn := range fns {
				if err := fn(brand_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mdmbrandsDescBrandLogo is the schema descriptor for brand_logo field.
	mdmbrandsDescBrandLogo := mdmbrandsFields[2].Descriptor()
	// mdmbrands.DefaultBrandLogo holds the default value on creation for the brand_logo field.
	mdmbrands.DefaultBrandLogo = mdmbrandsDescBrandLogo.Default.(string)
	// mdmbrands.BrandLogoValidator is a validator for the "brand_logo" field. It is called by the builders before save.
	mdmbrands.BrandLogoValidator = mdmbrandsDescBrandLogo.Validators[0].(func(string) error)
	// mdmbrandsDescBrandTitle is the schema descriptor for brand_title field.
	mdmbrandsDescBrandTitle := mdmbrandsFields[3].Descriptor()
	// mdmbrands.DefaultBrandTitle holds the default value on creation for the brand_title field.
	mdmbrands.DefaultBrandTitle = mdmbrandsDescBrandTitle.Default.(string)
	// mdmbrands.BrandTitleValidator is a validator for the "brand_title" field. It is called by the builders before save.
	mdmbrands.BrandTitleValidator = mdmbrandsDescBrandTitle.Validators[0].(func(string) error)
}
