// Code generated by ent, DO NOT EDIT.

package mdmbrands

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mdmbrands type in the database.
	Label = "mdm_brands"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "brand_id"
	// FieldBrandName holds the string denoting the brand_name field in the database.
	FieldBrandName = "brand_name"
	// FieldBrandLogo holds the string denoting the brand_logo field in the database.
	FieldBrandLogo = "brand_logo"
	// FieldBrandTitle holds the string denoting the brand_title field in the database.
	FieldBrandTitle = "brand_title"
	// Table holds the table name of the mdmbrands in the database.
	Table = "mdm_brands"
)

// Columns holds all SQL columns for mdmbrands fields.
var Columns = []string{
	FieldID,
	FieldBrandName,
	FieldBrandLogo,
	FieldBrandTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BrandNameValidator is a validator for the "brand_name" field. It is called by the builders before save.
	BrandNameValidator func(string) error
	// DefaultBrandLogo holds the default value on creation for the "brand_logo" field.
	DefaultBrandLogo string
	// BrandLogoValidator is a validator for the "brand_logo" field. It is called by the builders before save.
	BrandLogoValidator func(string) error
	// DefaultBrandTitle holds the default value on creation for the "brand_title" field.
	DefaultBrandTitle string
	// BrandTitleValidator is a validator for the "brand_title" field. It is called by the builders before save.
	BrandTitleValidator func(string) error
)

// OrderOption defines the ordering options for the MdmBrands queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBrandName orders the results by the brand_name field.
func ByBrandName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrandName, opts...).ToFunc()
}

// ByBrandLogo orders the results by the brand_logo field.
func ByBrandLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrandLogo, opts...).ToFunc()
}

// ByBrandTitle orders the results by the brand_title field.
func ByBrandTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrandTitle, opts...).ToFunc()
}
