// Code generated by ent, DO NOT EDIT.

package mdmbrands

import (
	"his/mdm/model/brands/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLTE(FieldID, id))
}

// BrandName applies equality check predicate on the "brand_name" field. It's identical to BrandNameEQ.
func BrandName(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandName, v))
}

// BrandLogo applies equality check predicate on the "brand_logo" field. It's identical to BrandLogoEQ.
func BrandLogo(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandLogo, v))
}

// BrandTitle applies equality check predicate on the "brand_title" field. It's identical to BrandTitleEQ.
func BrandTitle(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandTitle, v))
}

// BrandNameEQ applies the EQ predicate on the "brand_name" field.
func BrandNameEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandName, v))
}

// BrandNameNEQ applies the NEQ predicate on the "brand_name" field.
func BrandNameNEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNEQ(FieldBrandName, v))
}

// BrandNameIn applies the In predicate on the "brand_name" field.
func BrandNameIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldIn(FieldBrandName, vs...))
}

// BrandNameNotIn applies the NotIn predicate on the "brand_name" field.
func BrandNameNotIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNotIn(FieldBrandName, vs...))
}

// BrandNameGT applies the GT predicate on the "brand_name" field.
func BrandNameGT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGT(FieldBrandName, v))
}

// BrandNameGTE applies the GTE predicate on the "brand_name" field.
func BrandNameGTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGTE(FieldBrandName, v))
}

// BrandNameLT applies the LT predicate on the "brand_name" field.
func BrandNameLT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLT(FieldBrandName, v))
}

// BrandNameLTE applies the LTE predicate on the "brand_name" field.
func BrandNameLTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLTE(FieldBrandName, v))
}

// BrandNameContains applies the Contains predicate on the "brand_name" field.
func BrandNameContains(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContains(FieldBrandName, v))
}

// BrandNameHasPrefix applies the HasPrefix predicate on the "brand_name" field.
func BrandNameHasPrefix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasPrefix(FieldBrandName, v))
}

// BrandNameHasSuffix applies the HasSuffix predicate on the "brand_name" field.
func BrandNameHasSuffix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasSuffix(FieldBrandName, v))
}

// BrandNameEqualFold applies the EqualFold predicate on the "brand_name" field.
func BrandNameEqualFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEqualFold(FieldBrandName, v))
}

// BrandNameContainsFold applies the ContainsFold predicate on the "brand_name" field.
func BrandNameContainsFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContainsFold(FieldBrandName, v))
}

// BrandLogoEQ applies the EQ predicate on the "brand_logo" field.
func BrandLogoEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandLogo, v))
}

// BrandLogoNEQ applies the NEQ predicate on the "brand_logo" field.
func BrandLogoNEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNEQ(FieldBrandLogo, v))
}

// BrandLogoIn applies the In predicate on the "brand_logo" field.
func BrandLogoIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldIn(FieldBrandLogo, vs...))
}

// BrandLogoNotIn applies the NotIn predicate on the "brand_logo" field.
func BrandLogoNotIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNotIn(FieldBrandLogo, vs...))
}

// BrandLogoGT applies the GT predicate on the "brand_logo" field.
func BrandLogoGT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGT(FieldBrandLogo, v))
}

// BrandLogoGTE applies the GTE predicate on the "brand_logo" field.
func BrandLogoGTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGTE(FieldBrandLogo, v))
}

// BrandLogoLT applies the LT predicate on the "brand_logo" field.
func BrandLogoLT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLT(FieldBrandLogo, v))
}

// BrandLogoLTE applies the LTE predicate on the "brand_logo" field.
func BrandLogoLTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLTE(FieldBrandLogo, v))
}

// BrandLogoContains applies the Contains predicate on the "brand_logo" field.
func BrandLogoContains(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContains(FieldBrandLogo, v))
}

// BrandLogoHasPrefix applies the HasPrefix predicate on the "brand_logo" field.
func BrandLogoHasPrefix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasPrefix(FieldBrandLogo, v))
}

// BrandLogoHasSuffix applies the HasSuffix predicate on the "brand_logo" field.
func BrandLogoHasSuffix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasSuffix(FieldBrandLogo, v))
}

// BrandLogoEqualFold applies the EqualFold predicate on the "brand_logo" field.
func BrandLogoEqualFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEqualFold(FieldBrandLogo, v))
}

// BrandLogoContainsFold applies the ContainsFold predicate on the "brand_logo" field.
func BrandLogoContainsFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContainsFold(FieldBrandLogo, v))
}

// BrandTitleEQ applies the EQ predicate on the "brand_title" field.
func BrandTitleEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEQ(FieldBrandTitle, v))
}

// BrandTitleNEQ applies the NEQ predicate on the "brand_title" field.
func BrandTitleNEQ(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNEQ(FieldBrandTitle, v))
}

// BrandTitleIn applies the In predicate on the "brand_title" field.
func BrandTitleIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldIn(FieldBrandTitle, vs...))
}

// BrandTitleNotIn applies the NotIn predicate on the "brand_title" field.
func BrandTitleNotIn(vs ...string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldNotIn(FieldBrandTitle, vs...))
}

// BrandTitleGT applies the GT predicate on the "brand_title" field.
func BrandTitleGT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGT(FieldBrandTitle, v))
}

// BrandTitleGTE applies the GTE predicate on the "brand_title" field.
func BrandTitleGTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldGTE(FieldBrandTitle, v))
}

// BrandTitleLT applies the LT predicate on the "brand_title" field.
func BrandTitleLT(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLT(FieldBrandTitle, v))
}

// BrandTitleLTE applies the LTE predicate on the "brand_title" field.
func BrandTitleLTE(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldLTE(FieldBrandTitle, v))
}

// BrandTitleContains applies the Contains predicate on the "brand_title" field.
func BrandTitleContains(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContains(FieldBrandTitle, v))
}

// BrandTitleHasPrefix applies the HasPrefix predicate on the "brand_title" field.
func BrandTitleHasPrefix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasPrefix(FieldBrandTitle, v))
}

// BrandTitleHasSuffix applies the HasSuffix predicate on the "brand_title" field.
func BrandTitleHasSuffix(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldHasSuffix(FieldBrandTitle, v))
}

// BrandTitleEqualFold applies the EqualFold predicate on the "brand_title" field.
func BrandTitleEqualFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldEqualFold(FieldBrandTitle, v))
}

// BrandTitleContainsFold applies the ContainsFold predicate on the "brand_title" field.
func BrandTitleContainsFold(v string) predicate.MdmBrands {
	return predicate.MdmBrands(sql.FieldContainsFold(FieldBrandTitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MdmBrands) predicate.MdmBrands {
	return predicate.MdmBrands(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MdmBrands) predicate.MdmBrands {
	return predicate.MdmBrands(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MdmBrands) predicate.MdmBrands {
	return predicate.MdmBrands(sql.NotPredicates(p))
}
