// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MdmBrandsColumns holds the columns for the "mdm_brands" table.
	MdmBrandsColumns = []*schema.Column{
		{Name: "brand_id", Type: field.TypeInt, Increment: true},
		{Name: "brand_name", Type: field.TypeString, Size: 50, Comment: "品牌名称"},
		{Name: "brand_logo", Type: field.TypeString, Size: 255, Comment: "品牌logo222", Default: ""},
		{Name: "brand_title", Type: field.TypeString, Size: 255, Comment: "品牌标题", Default: ""},
	}
	// MdmBrandsTable holds the schema information for the "mdm_brands" table.
	MdmBrandsTable = &schema.Table{
		Name:       "mdm_brands",
		Comment:    "基础物料品牌222",
		Columns:    MdmBrandsColumns,
		PrimaryKey: []*schema.Column{MdmBrandsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MdmBrandsTable,
	}
)

func init() {
}
