// Code generated by goctl. DO NOT EDIT.
// Source: mdm.proto

package mdmbrandservice

import (
	"context"

	"his/mdm/rpc/mdm"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyRequest         = mdm.EmptyRequest
	EmptyResponse        = mdm.EmptyResponse
	MdmBrandInfo         = mdm.MdmBrandInfo
	MdmBrandInfoRequest  = mdm.MdmBrandInfoRequest
	MdmBrandListRequest  = mdm.MdmBrandListRequest
	MdmBrandListResponse = mdm.MdmBrandListResponse
	TotalResponse        = mdm.TotalResponse

	MdmBrandService interface {
		// 品牌数量
		MdmBrandCount(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*TotalResponse, error)
		// 品牌列表
		MdmBrandList(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*MdmBrandListResponse, error)
		// 品牌信息
		MdmBrandDetails(ctx context.Context, in *MdmBrandInfoRequest, opts ...grpc.CallOption) (*MdmBrandInfo, error)
		// 品牌增加
		MdmBrandAdd(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error)
		// 品牌修改
		MdmBrandUpdate(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error)
	}

	defaultMdmBrandService struct {
		cli zrpc.Client
	}
)

func NewMdmBrandService(cli zrpc.Client) MdmBrandService {
	return &defaultMdmBrandService{
		cli: cli,
	}
}

// 品牌数量
func (m *defaultMdmBrandService) MdmBrandCount(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*TotalResponse, error) {
	client := mdm.NewMdmBrandServiceClient(m.cli.Conn())
	return client.MdmBrandCount(ctx, in, opts...)
}

// 品牌列表
func (m *defaultMdmBrandService) MdmBrandList(ctx context.Context, in *MdmBrandListRequest, opts ...grpc.CallOption) (*MdmBrandListResponse, error) {
	client := mdm.NewMdmBrandServiceClient(m.cli.Conn())
	return client.MdmBrandList(ctx, in, opts...)
}

// 品牌信息
func (m *defaultMdmBrandService) MdmBrandDetails(ctx context.Context, in *MdmBrandInfoRequest, opts ...grpc.CallOption) (*MdmBrandInfo, error) {
	client := mdm.NewMdmBrandServiceClient(m.cli.Conn())
	return client.MdmBrandDetails(ctx, in, opts...)
}

// 品牌增加
func (m *defaultMdmBrandService) MdmBrandAdd(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := mdm.NewMdmBrandServiceClient(m.cli.Conn())
	return client.MdmBrandAdd(ctx, in, opts...)
}

// 品牌修改
func (m *defaultMdmBrandService) MdmBrandUpdate(ctx context.Context, in *MdmBrandInfo, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := mdm.NewMdmBrandServiceClient(m.cli.Conn())
	return client.MdmBrandUpdate(ctx, in, opts...)
}
