// Code generated by goctl. DO NOT EDIT.
// Source: mdm.proto

package server

import (
	"context"

	"his/mdm/rpc/internal/logic/mdmbrandservice"
	"his/mdm/rpc/internal/svc"
	"his/mdm/rpc/mdm"
)

type MdmBrandServiceServer struct {
	svcCtx *svc.ServiceContext
	mdm.UnimplementedMdmBrandServiceServer
}

func NewMdmBrandServiceServer(svcCtx *svc.ServiceContext) *MdmBrandServiceServer {
	return &MdmBrandServiceServer{
		svcCtx: svcCtx,
	}
}

// 品牌数量
func (s *MdmBrandServiceServer) MdmBrandCount(ctx context.Context, in *mdm.MdmBrandListRequest) (*mdm.TotalResponse, error) {
	l := mdmbrandservicelogic.NewMdmBrandCountLogic(ctx, s.svcCtx)
	return l.MdmBrandCount(in)
}

// 品牌列表
func (s *MdmBrandServiceServer) MdmBrandList(ctx context.Context, in *mdm.MdmBrandListRequest) (*mdm.MdmBrandListResponse, error) {
	l := mdmbrandservicelogic.NewMdmBrandListLogic(ctx, s.svcCtx)
	return l.MdmBrandList(in)
}

// 品牌信息
func (s *MdmBrandServiceServer) MdmBrandDetails(ctx context.Context, in *mdm.MdmBrandInfoRequest) (*mdm.MdmBrandInfo, error) {
	l := mdmbrandservicelogic.NewMdmBrandDetailsLogic(ctx, s.svcCtx)
	return l.MdmBrandDetails(in)
}

// 品牌增加
func (s *MdmBrandServiceServer) MdmBrandAdd(ctx context.Context, in *mdm.MdmBrandInfo) (*mdm.EmptyResponse, error) {
	l := mdmbrandservicelogic.NewMdmBrandAddLogic(ctx, s.svcCtx)
	return l.MdmBrandAdd(in)
}

// 品牌修改
func (s *MdmBrandServiceServer) MdmBrandUpdate(ctx context.Context, in *mdm.MdmBrandInfo) (*mdm.EmptyResponse, error) {
	l := mdmbrandservicelogic.NewMdmBrandUpdateLogic(ctx, s.svcCtx)
	return l.MdmBrandUpdate(in)
}
