// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package branch

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mdmBranchFieldNames          = builder.RawFieldNames(&MdmBranch{}, true)
	mdmBranchRows                = strings.Join(mdmBranchFieldNames, ",")
	mdmBranchRowsExpectAutoSet   = strings.Join(stringx.Remove(mdmBranchFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	mdmBranchRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(mdmBranchFieldNames, "branch_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	mdmBranchModel interface {
		Insert(ctx context.Context, data *MdmBranch) (sql.Result, error)
		FindOne(ctx context.Context, branchId int64) (*MdmBranch, error)
		FindOneByBranchBn(ctx context.Context, branchBn string) (*MdmBranch, error)
		Update(ctx context.Context, data *MdmBranch) error
		Delete(ctx context.Context, branchId int64) error
	}

	defaultMdmBranchModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MdmBranch struct {
		BranchId           int64          `db:"branch_id"`
		WmsId              sql.NullInt64  `db:"wms_id"`
		BranchBn           string         `db:"branch_bn"`
		StorageCode        string         `db:"storage_code"`
		Name               string         `db:"name"`
		ParentId           sql.NullInt64  `db:"parent_id"`
		Type               string         `db:"type"`
		Disabled           string         `db:"disabled"`
		Area               sql.NullString `db:"area"`
		Address            sql.NullString `db:"address"`
		Zip                sql.NullString `db:"zip"`
		Phone              sql.NullString `db:"phone"`
		Uname              sql.NullString `db:"uname"`
		Mobile             sql.NullString `db:"mobile"`
		Sex                sql.NullString `db:"sex"`
		Memo               sql.NullString `db:"memo"`
		StockThreshold     sql.NullInt64  `db:"stock_threshold"`
		StockSafeType      sql.NullString `db:"stock_safe_type"`
		StockSafeDay       sql.NullInt64  `db:"stock_safe_day"`
		StockSafeTime      sql.NullInt64  `db:"stock_safe_time"`
		Attr               sql.NullString `db:"attr"`
		Online             sql.NullString `db:"online"`
		Weight             sql.NullInt64  `db:"weight"`
		Defaulted          string         `db:"defaulted"`
		AreaConf           sql.NullString `db:"area_conf"`
		IsDelivBranch      sql.NullString `db:"is_deliv_branch"`
		BindConf           sql.NullString `db:"bind_conf"`
		Owner              sql.NullString `db:"owner"`
		IsDeclare          sql.NullString `db:"is_declare"`
		BType              sql.NullInt64  `db:"b_type"`
		BStatus            sql.NullInt64  `db:"b_status"`
		LogisticsLimitTime sql.NullInt64  `db:"logistics_limit_time"`
		StartWork          sql.NullString `db:"start_work"`
		EndWork            sql.NullString `db:"end_work"`
		Ability            sql.NullInt64  `db:"ability"`
		CutoffTime         sql.NullString `db:"cutoff_time"`
	}
)

func newMdmBranchModel(conn sqlx.SqlConn) *defaultMdmBranchModel {
	return &defaultMdmBranchModel{
		conn:  conn,
		table: `"public"."mdm_branch"`,
	}
}

func (m *defaultMdmBranchModel) Delete(ctx context.Context, branchId int64) error {
	query := fmt.Sprintf("delete from %s where branch_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, branchId)
	return err
}

func (m *defaultMdmBranchModel) FindOne(ctx context.Context, branchId int64) (*MdmBranch, error) {
	query := fmt.Sprintf("select %s from %s where branch_id = $1 limit 1", mdmBranchRows, m.table)
	var resp MdmBranch
	err := m.conn.QueryRowCtx(ctx, &resp, query, branchId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdmBranchModel) FindOneByBranchBn(ctx context.Context, branchBn string) (*MdmBranch, error) {
	var resp MdmBranch
	query := fmt.Sprintf("select %s from %s where branch_bn = $1 limit 1", mdmBranchRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, branchBn)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMdmBranchModel) Insert(ctx context.Context, data *MdmBranch) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36)", m.table, mdmBranchRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BranchId, data.WmsId, data.BranchBn, data.StorageCode, data.Name, data.ParentId, data.Type, data.Disabled, data.Area, data.Address, data.Zip, data.Phone, data.Uname, data.Mobile, data.Sex, data.Memo, data.StockThreshold, data.StockSafeType, data.StockSafeDay, data.StockSafeTime, data.Attr, data.Online, data.Weight, data.Defaulted, data.AreaConf, data.IsDelivBranch, data.BindConf, data.Owner, data.IsDeclare, data.BType, data.BStatus, data.LogisticsLimitTime, data.StartWork, data.EndWork, data.Ability, data.CutoffTime)
	return ret, err
}

func (m *defaultMdmBranchModel) Update(ctx context.Context, newData *MdmBranch) error {
	query := fmt.Sprintf("update %s set %s where branch_id = $1", m.table, mdmBranchRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.BranchId, newData.WmsId, newData.BranchBn, newData.StorageCode, newData.Name, newData.ParentId, newData.Type, newData.Disabled, newData.Area, newData.Address, newData.Zip, newData.Phone, newData.Uname, newData.Mobile, newData.Sex, newData.Memo, newData.StockThreshold, newData.StockSafeType, newData.StockSafeDay, newData.StockSafeTime, newData.Attr, newData.Online, newData.Weight, newData.Defaulted, newData.AreaConf, newData.IsDelivBranch, newData.BindConf, newData.Owner, newData.IsDeclare, newData.BType, newData.BStatus, newData.LogisticsLimitTime, newData.StartWork, newData.EndWork, newData.Ability, newData.CutoffTime)
	return err
}

func (m *defaultMdmBranchModel) tableName() string {
	return m.table
}
